# Generated by Django 2.1.5 on 2019-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='имя продукта'),
        ),
    ]
