# Generated by Django 2.1.1 on 2019-01-19 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190119_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 19, 38, 32, 743593, tzinfo=utc)),
        ),
    ]
