# Generated by Django 2.1.1 on 2019-01-20 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190119_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 23, 10, 11, 19030, tzinfo=utc)),
        ),
    ]
