# Generated by Django 2.1.1 on 2019-01-20 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190121_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 23, 39, 15, 616266, tzinfo=utc)),
        ),
    ]
